### PR TITLE
add specific sysreqs for INLA installation

### LINKED ISSUE #117: Elaborate if INLA, JAGS and GSL can be installed via SystemRequirements

### PR DESCRIPTION
**Pull request by matteodelucchi**
- closes #117

### CODE REVIEW

**Comment by j-i-l** [comment]
It seems we are missing `R6` package in Fedora:

https://github.com/furrer-lab/abn/actions/runs/10109199488/job/27956597053#step:16:146

Adding this to the `Suggests`

**Comment by j-i-l** [comment]
Moving `entropy` and `moments` back to suggests.

See Warning:
https://github.com/furrer-lab/abn/actions/runs/10109199488/job/27956597053#step:16:178

**Comment by j-i-l** [comment]
Hm, running `devtools::check` on Fedora complains about `R6` not being installed (https://github.com/furrer-lab/abn/actions/runs/10109701871/job/27958155516#step:16:146)
even though it is installed.
Then, when adding `R6` to `Depends`, the installation from GitHub and from source still works, how `devtools::check` is apparently not able to install `abn` anymore (https://github.com/furrer-lab/abn/actions/runs/10112877064/job/27967944136#step:16:61) :frowning_face: 

I'll switch to running `rcmdcheck::rcmdcheck` directly and see if we have more luck with this.

**Comment by j-i-l** [comment]
`fmesher` fails now for INLA install (missing `sf` package... again) :face_exhaling:

**Comment by j-i-l** [comment]
it seems we are back to square 1:

installation form GitHub report `udunits` and others missing... it seems the libraries are not installed...

https://github.com/furrer-lab/abn/actions/runs/10115569396/job/27976641368#step:12:1437

**Comment by j-i-l** [comment]
it seems to me that `SystemRequirements` are completely ignored when installing form GitHub...

**Comment by j-i-l** [comment]
Fails also when installing from source

https://github.com/furrer-lab/abn/actions/runs/10115569396/job/27976641368#step:15:86

**Comment by j-i-l** [comment]
Trying with `pak` leads to unsolvable dependency issue with R 4.3..

Same as:
https://github.com/microsoft/LightGBM/issues/6433

Pinning the version for `Matrix` to `1.6.0` does not have any effect, even if the req. for this version is R >= 3... .

**Comment by j-i-l** [comment]
Ok, this article sheds some light on how the r-system-requirements repo is actually used.

We might want to setup the installation with `pak` if we want to use `SystemRequirements`

**Comment by matteodelucchi** [comment]
> Ok, this article sheds some light on how the r-system-requirements repo is actually used.
> 
> We might want to setup the installation with `pak` if we want to use `SystemRequirements`

the link to the article is missing.

**Comment by j-i-l** [comment]
:sweat_smile: https://blog.r-hub.io/2023/09/26/system-dependency/#the-general-case-everything-works-automagically

**Comment by j-i-l** [comment]
https://github.com/furrer-lab/abn/actions/runs/10132319987/job/28016164210#step:11:595

Nice! `pak` seems to pick up our system dependencies! :crossed_fingers:

**Comment by j-i-l** [comment]
Ok, now INLA is not found. It seems `pak` does not process the `Additional_repositories` from the DESC... file.

But we might try to add it manually...

**Comment by j-i-l** [comment]
...and `pak` fails when trying to install dependency `Matrix`:
https://github.com/furrer-lab/abn/actions/runs/10133347609/job/28018413666#step:12:26

even on R 4.4.

**Comment by j-i-l** [comment]
INLA is there: https://github.com/furrer-lab/abn/actions/runs/10133524596/job/28018767814#step:12:1063

**Comment by j-i-l** [comment]
Nice:

- `cmake` is installed: https://github.com/furrer-lab/abn/actions/runs/10133887086/job/28019520620#step:10:718
- `gsl` is installed: https://github.com/furrer-lab/abn/actions/runs/10133887086/job/28019520620#step:10:722
- `Rgraphviz` from BiocManager is installed: https://github.com/furrer-lab/abn/actions/runs/10133887086/job/28019520620#step:10:1296

It seems for Fedora we are down to:

- install curl prior to `pak` installation (as it fails otherwise)
- install JAGS from source and fixing runtime linkage.

Let's see how far we get with Ubuntu

**Comment by j-i-l** [comment]
`testthat` under Ubuntu complains that `ex0/1` are not exported objects under namespace abn.

**Comment by j-i-l** [comment]
We're back to #134

**Comment by j-i-l** [comment]
Now we need to adapt the installation instructions

**Comment by j-i-l** [comment]
Done with the installation instructions.

**Pull request merged**
